version: "3.7"
services:
  mysqldb:
    container_name: mysqldb
    image: "mysql:8.0"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: basics
      MYSQL_USER: amila_one
      MYSQL_PASSWORD: Amila_pw
      MYSQL_ROOT_PASSWORD: Amila_pw

  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/basics?allowPublicKeyRetrieval=true
      - spring.datasource.username=amila_one
      - spring.datasource.password=Amila_pw
    depends_on:
      - mysqldb

    volumes:
      - .m2:/root/.m2
networks:
  springapimysql-net:
      driver: overlay
      attachable: true
